FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# UTOP

uTOP - API for system for shift planning in multi-shift 

## Multiple users [/multipleUsers] 

### Create multiple users

+ Request (application/json)

            [   
                {
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "1",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "1",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment": "{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                },
                {
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]
            
+ Response 200 (application/json)

## Users Collection [/user]

+ empolyeeID (int) - Employee ID
+ firstName (string) - Employee name
+ surname (string) - Employee surname
+ role (int) - User role in system
+ orgUnit { id: (int), name: (string) } - Org. unit which the employee is assigned to
+ createdOn (datetime) - date of user creation 
+ createdBy { id: (int), name: (string) } - 
+ email (string) - Employee email 
+ phoneNumber (string) - Employee email 
+ uniqueEmployeeID (string) - Employee unique ID from external system
+ weekendWork (bit) - Weekend shifts allowed to employee
+ workRestriction (string) - Informative note about employees work restrictions
+ employment { id: (int), name: (string) } 
+ workTime (int) - In hours 
+ photoUrl (string) - Employee photo
+ active (bit) 
+ validTo (datetime)
+ primarySkill { id: (int), name: (string) } - Employee primary skill from table Skills
+ secondarySkill { id: (int), name: (string) } - Employee secondary skill from table Skills
+ preferedShifts (array  [{ id: (int), name: (string)] } 

### List All Users [GET]

+ Attributes 

    + empolyeeID (number) - Employee ID
    + firstName (string) - Employee name
    + surname (string) - Employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - Org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of User
    + email (string) - Employee email 
    + phoneNumber (string) - Employee email 
    + uniqueEmployeeID (string) - Employee unique ID from external system
    + weekendWork (number) - Weekend shifts allowed to employee
    + workRestriction (string) - Informative note about employees work restrictions
    + employment (array [number, string]) 
    + workTime (number) - In hours 
    + photoUrl (string) - Employee photo
    + active (number) 
    + validTo (string)
    + primarySkill (array [number, string]) - Employee primary skill from table Skills
    + secondarySkill (array [number, string]) - Employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) 

+ Response 200 (application/json) 

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

### Create User [POST]

+ Request (application/json)

            {
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "1",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "1",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }

+ Response 201 (application/json)

    + Headers

            Location: /user/1

    + Body

            {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }
            
## User - Login [/user/login]

### Login User [POST]

Login user 

+ Request (application/json)
        
            {
                "uniqueEmployeeID": "uTOP00001",
                "password": "supertajneheslo",
                "ttl": 1209600000
            }

+ Response 200 (application/json)

            {
                "id": "PqosmmPCdQgwerDYwQcVCxMakGQV0BSUwG4iGVLvD3XUYZRQky1cmG8ocmzsVpEE",
                "ttl": 1209600,
                "created": "2014-12-23T08:31:33.464Z",
                "userId": 1
            }
            
## User - Logout [/user/logout]

### Logout User [GET]

Logout user

+ Response 200 (application/json)

        OK

## User - Collection [/user/user_id={user_id}]

### Update User [PUT]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

+ Request (application/json)
    
            {
                "employeeID": "1"
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
            }

+ Response 200 (application/json) 

### User Detail [GET]

View detail about user with id in param

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    
+ Response 200 (application/json)

            {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z"
            }

### Delete User [DELETE]

Change User active attribute active to false

+ Parameters

    + user_id (number) - ID of the User in the form of an integer

+ Response 200 (application/json)

            {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "false",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }        

## User - ChangeMyPhoto [/user/user_id={user_id}/changeMyPhoto]

### ChangeMyPhoto [POST]

+ Request (application/json)

            { 
            }

+ Response 201 (application/json)

            {
            }

## User - ChangePassword [/user/user_id={user_id}/changePassword]

### ChangePassword [POST]

+ Parameters

    + user_id (number) - ID of the User in the form of an integer
    
+ Request (application/json)

            {
                "password":{
                "oldPassword":"test@123",
                "newPassword":"test@321"
                }
            }

+ Response 200 (application/json)

            {
                "password":{
                "oldPassword":"test@123",
                "newPassword":"test@321"
                }
            }
            
## User - ForgotPassword [/user/forgotPassword]

### ForgotPassword [POST]

+ Request (application/json) 

            {
            "email": "martin.vantara@principal.cz"
            }

+ Response 200 (application/json)

## User - ForgotID [/user/forgotID]

### ForgotID [POST]

+ Request (application/json) 

            {
            "email": "martin.vantara@principal.cz"
            }

+ Response 200 (application/json) 

## Organzation chart Collection [/orgunit]

+ orgUnitID (int) - Org. unit ID
+ active (bit) - Org. unit is active/deleted
+ name (string) - Org. unit name
+ orgUnitManager ( id: (int), name: (string) )
+ orgUnitManagerDeputy ( id: (int), name: (string) )
+ servicePoints (int) 
+ shiftType ( [{ id: (int), name: (string)}] )
+ SLA (int)
+ waitingTime (int) 
+ avgServiceTime (int) 
+ otherTasks (int) 
+ skills ( [{ id: (int), name: (string)}] )  
+ street (string) 
+ landRegistryNumber (int) - číslo popisné
+ houseNumber (int) - číslo orientační
+ city (string) 
+ country (string) 
+ phoneNumber (string)

### Create Organization unit [POST]

+ Request (application/json)

            {
                "name": "Praha",
                "active": "true", 
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

+ Response 201 (application/json) 

    + Headers

            Location: /orgunit/1

    + Body
    
            {
                
                "orgUnitID": "1", 
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

## OU - Collection [/orgunit/orgUnitID={orgUnitID}]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

### Organization unit update [PUT]

+ Request (application/json)

            {
                "orgUnitID": "1",
                "active": "true",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

+ Response 200 (application/json)

### Organization unit detail [GET]

View detail about org.unit with id in param

+ Parameters

    + orgUnitID (number) - ID of the Org.Unit in the form of an integer
    
+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "active": "true",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

### Organization unit delete [DELETE]

+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "active": "false",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

## OU - AssignableEmployees [/orgunit/orgUnitID={orgUnitID}/assignableEmployees]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

### AssignableEmployees [GET]

+ Response 200 (application/json)

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

## OU - AssignedEmployees [/orgunit/orgUnitID={orgUnitID}/assignedEmployees]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

### AssignedEmployees [GET]

+ Response 200 (application/json)

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

## OU - OrgUnitShiftType Collection [/orgunit/orgUnitID={orgUnitID}/orgUnitShiftType]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

### OrgUnitShiftType Create [POST]

+ Request (application/json) 

            {
                "shiftType" : {
                    "name": "15",
                    "length": "15",
                    "active": "true"
                }
            }

+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }, {
                                "id" : "4", 
                                "name" : "15"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }
            
### OrgUnitShiftType All [GET]

+ Response 200 (application/json)

            {
                "shiftType" : {
                    "name": "15",
                    "length": "15",
                    "active": "true"
                },
                "shiftType" : {
                    "name": "6",
                    "length": "6",
                    "active": "true"
                },
                "shiftType" : {
                    "name": "8",
                    "length": "8",
                    "active": "false"
                }
            }

## OU - OrgUnitShiftType [/orgunit/orgUnit_id={orgUnit_id}/orgUnitShiftType/orgUnitShiftType_id={orgUnitShiftType_id}]

### OrgUnitShiftType Delete [DELETE]

Change orgUnitShiftType active attribute to false

+ Parameters

    + orgUnitShiftType_id (number) - ID of the orgUnitShiftType in the form of an integer

+ Response 200 (application/json)

            {
                "shiftType" : {
                    "name": "15",
                    "length": "15",
                    "active": "false"
                }
            }















