FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# UTOP

uTOP - API for system for shift planning in multi-shift 

## Multiple users [/multipleUsers] 

### Create multiple users

+ Request (application/json)

            [   
                {
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "1",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "1",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment": "{ "id": 1, "name": "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ "id": 1, "name": "Pokladní" }",
                "secondarySkill": "{ "id": 2, "name": "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                },
                {
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ "id": 1, "name": "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ "id": 3, "name": "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ "id": 1, "name": "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ "id": 1, "name": "Pokladní" }",
                "secondarySkill": "{ "id": 2, "name": "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]
            
+ Response 200 (application/json)

## Users Collection [/user]

### List All Users [GET]

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Response 200 (application/json) 

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

### Create User [POST]

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Request (application/json)

            {
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "1",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "1",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }

+ Response 201 (application/json)

    + Headers

            Location: /user/1

    + Body

            {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }
            
## User - Login [/user/login]

### Login User [POST]

Login user 

+ Attributes 

    + uniqueEmployeeID (string) - user login id 
    + password (string) - user password 
    + ttl (number) - time to live 

+ Request (application/json)
        
            {
                "uniqueEmployeeID": "uTOP00001",
                "password": "supertajneheslo",
                "ttl": 1209600000
            }

+ Response 200 (application/json)

            {
                "id": "PqosmmPCdQgwerDYwQcVCxMakGQV0BSUwG4iGVLvD3XUYZRQky1cmG8ocmzsVpEE",
                "ttl": 1209600,
                "created": "2014-12-23T08:31:33.464Z",
                "userId": 1
            }
            
## User - Logout [/user/logout]

### Logout User [GET]

Logout user

+ Response 200 (application/json)

        OK

## User - Collection [/user/user_id={user_id}]

### Update User [PUT]

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

+ Request (application/json)
    
            {
                "employeeID": "1"
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
            }

+ Response 200 (application/json) 

### User Detail [GET]

View detail about user with id in param

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Parameters

    + user_id (number) - ID of the User in the form of an integer
    
+ Response 200 (application/json)

            {
                "employeeID": "1"
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
            }

### Delete User [DELETE]

Change User active attribute active to false

+ Parameters

    + user_id (number) - ID of the User in the form of an integer

+ Response 200 (application/json)

            {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnit": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photoUrl": "bla",
                "active": "false",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
            }        

## User - ChangeMyPhoto [/user/user_id={user_id}/changeMyPhoto]

### ChangeMyPhoto [POST]

+ Request (application/json)

            { 
            }

+ Response 201 (application/json)

            {
            }

## User - ChangePassword [/user/user_id={user_id}/changePassword]

### ChangePassword [POST]

+ Attributes

    + oldPassword (string) 
    + newPassword (string) 

+ Parameters

    + user_id (number) - ID of the User in the form of an integer
    
+ Request (application/json)

            {
                "password":{
                "oldPassword":"test@123",
                "newPassword":"test@321"
                }
            }

+ Response 200 (application/json)

            {
                "password":{
                "oldPassword":"test@123",
                "newPassword":"test@321"
                }
            }
            
## User - ForgotPassword [/user/forgotPassword]

### ForgotPassword [POST]

+ Attributes

    + email (string) - email adress of user

+ Request (application/json) 

            {
            "email": "martin.vantara@principal.cz"
            }

+ Response 200 (application/json)

## User - ForgotID [/user/forgotID]

### ForgotID [POST]

+ Attributes

    + email (string) - email adress of user

+ Request (application/json) 

            {
            "email": "martin.vantara@principal.cz"
            }

+ Response 200 (application/json) 

## Organzation chart Collection [/orgunit]

### Create Organization unit [POST]

+ Attributes 

    + orgUnitID (number) - org. unit ID
    + active (number) - org. unit is active/deleted
    + name (string) - org. unit name
    + orgUnitManager ( array [number, string] ) 
    + orgUnitManagerDeputy ( array [number, string] )
    + servicePoints (number) 
    + shiftType ( array [number, string] )
    + SLA (number) - Service-level agreement in %
    + waitingTime (number) - waiting time in seconds 
    + avgServiceTime (number) - waiting time in seconds
    + otherTasks (number) - value in %
    + skills ( array [number, string] ) - skills required in org. unit 
    + street (string) 
    + landRegistryNumber (number) - číslo popisné
    + houseNumber (number) - číslo orientační
    + city (string)  
    + country (string) 
    + phoneNumber (string)
    
+ Request (application/json)

            {
                "name": "Praha",
                "active": "true", 
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

+ Response 201 (application/json) 

    + Headers

            Location: /orgunit/1

    + Body
    
            {
                
                "orgUnitID": "1", 
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

## OU - Collection [/orgunit/orgUnitID={orgUnitID}]



### Organization unit update [PUT]

+ Attributes 

    + orgUnitID (number) - org. unit ID
    + active (number) - org. unit is active/deleted
    + name (string) - org. unit name
    + orgUnitManager ( array [number, string] ) 
    + orgUnitManagerDeputy ( array [number, string] )
    + servicePoints (number) 
    + shiftType ( array [number, string] )
    + SLA (number) - Service-level agreement in %
    + waitingTime (number) - waiting time in seconds 
    + avgServiceTime (number) - waiting time in seconds
    + otherTasks (number) - value in %
    + skills ( array [number, string] ) - skills required in org. unit 
    + street (string) 
    + landRegistryNumber (number) - číslo popisné
    + houseNumber (number) - číslo orientační
    + city (string)  
    + country (string) 
    + phoneNumber (string)

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Request (application/json)

            {
                "orgUnitID": "1",
                "active": "true",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

+ Response 200 (application/json)

### Organization unit detail [GET]

View detail about org.unit with id in param

+ Attributes 

    + orgUnitID (number) - org. unit ID
    + active (number) - org. unit is active/deleted
    + name (string) - org. unit name
    + orgUnitManager ( array [number, string] ) 
    + orgUnitManagerDeputy ( array [number, string] )
    + servicePoints (number) 
    + shiftType ( array [number, string] )
    + SLA (number) - Service-level agreement in %
    + waitingTime (number) - waiting time in seconds 
    + avgServiceTime (number) - waiting time in seconds
    + otherTasks (number) - value in %
    + skills ( array [number, string] ) - skills required in org. unit 
    + street (string) 
    + landRegistryNumber (number) - číslo popisné
    + houseNumber (number) - číslo orientační
    + city (string)  
    + country (string) 
    + phoneNumber (string)

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer
    
+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "active": "true",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

### Organization unit delete [DELETE]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "active": "false",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }

## OU - AssignableEmployees [/orgunit/orgUnitID={orgUnitID}/assignableEmployees]

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

### AssignableEmployees [GET]

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Response 200 (application/json)

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

## OU - AssignedEmployees [/orgunit/orgUnitID={orgUnitID}/assignedEmployees]

### AssignedEmployees [GET]

+ Attributes 

    + empolyeeID (number) - employee ID
    + firstName (string) - employee name
    + surname (string) - employee surname
    + role (number) - User role in system
    + orgUnit (array [number, string]) - org. unit which the employee is assigned to
    + createdOn (string) - date of user creation 
    + createdBy (array [number, string]) - ID and name of user, who created this employee 
    + email (string) - employee email 
    + phoneNumber (string) - employee phone number 
    + uniqueEmployeeID (string) - employee unique ID from external system
    + weekendWork (number) - weekend shifts allowed to employee
    + workRestriction (string) - informative note about employees work restrictions
    + employment (array [number, string]) - value from enum employment
    + workTime (number) - work time in hours per week
    + photoUrl (string) - employee photo
    + active (number) - value true/ false
    + validTo (string) - 
    + primarySkill (array [number, string]) - employee primary skill from table Skills
    + secondarySkill (array [number, string]) - employee secondary skill from table Skills
    + preferedShifts (array  [number,string]) - employee prefered shifts from table EmployeePreferedShifts

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Response 200 (application/json)

            [
                {
                "employeeID": "1",
                "firstName": "Martin",
                "surname": "Vantara",
                "roleID": "1",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-11T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.vantara@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00001",
                "weekendWork": "false",
                "workRestriction": "Nemôže pracovať v noci.",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-11T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Odpolední"
                                }
                                    ] 
                },
                {
                "employeeID": "2",
                "firstName": "Martin",
                "surname": "May",
                "roleID": "2",
                "orgUnitID": "{ id: 1, name: "Praha" }",
                "createdOn": "2014-11-15T08:40:51.620Z",
                "createdBy": "{ id: 3, name: "Michal Novák" }",
                "email": "martin.may@principal.cz",
                "phoneNumber": "+420773214674",
                "uniqueEmployeeID": "uTOP00002",
                "weekendWork": "true",
                "workRestriction": "Super manažér",
                "employment":"{ id: 1, name: "Zaměstnanec" }",
                "workTime": "40",
                "photo": "bla",
                "active": "true",
                "validTo": "2020-11-13T08:40:51.620Z",
                "primarySkill": "{ id: 1, name: "Pokladní" }",
                "secondarySkill": "{ id: 2, name: "Hlavní pokladní" }",
                "preferedShifts":   [
                                {
                                "id" : "1", 
                                "name" : "Ranní"
                                }, {
                                "id" : "2", 
                                "name" : "Noční"
                                }
                                    ] 
                }
            ]

## OU - OrgUnitShiftType Collection [/orgunit/orgUnitID={orgUnitID}/orgUnitShiftType]

### OrgUnitShiftType Create [POST]

+ Attributes 

    + id (number) - 
    + name (string) - 
    + length (number) - length of shift in hours 
    + active (number) - shift type is active true/ false

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Request (application/json) 

            {
                "shiftType" : {
                    "name": "15",
                    "length": "15",
                    "active": "true"
                }
            }

+ Response 200 (application/json)

            {
                "orgUnitID": "1",
                "name": "Praha",
                "orgUnitManager": "{ id: 1, name: "Martin Vantara" }",
                "orgUnitManagerDeputy": "{ id: 2, name: "Martin May" }",
                "servicePoints": "3",
                "shiftType": [
                                {
                                "id" : "1", 
                                "name" : "4"
                                }, {
                                "id" : "2", 
                                "name" : "6"
                                }, {
                                "id" : "3", 
                                "name" : "8"
                                }, {
                                "id" : "4", 
                                "name" : "15"
                                }
                            ],
                "SLA": "95",
                "waitingTime": "300",
                "avgServiceTime": "240",
                "otherTasks": "10",
                "skills": [
                                {
                                "id" : "1", 
                                "name" : "Pokladní"
                                }, {
                                "id" : "2", 
                                "name" : "Hlavní pokladní"
                                }
                            ],
                "street": "Lodžská",
                "landRegistryNumber": "3",
                "houseNumber": "923",
                "city": "Praha",
                "country": "Česká republika", 
                "phoneNumber": "+420 774 928 742"
            }
            
### OrgUnitShiftType All [GET]

+ Attributes 

    + id (number) - 
    + name (string) - 
    + length (number) - length of shift in hours 
    + active (number) - shift type is active true/ false

+ Parameters

    + orgUnitID (int) - Org.unit ID in the form of integer

+ Response 200 (application/json)

            {
                "shiftType" : {
                    "id": "1",
                    "name": "15",
                    "length": "15",
                    "active": "true"
                },
                "shiftType" : {
                    "id": "2",
                    "name": "6",
                    "length": "6",
                    "active": "true"
                },
                "shiftType" : {
                    "id": "2",
                    "name": "8",
                    "length": "8",
                    "active": "false"
                }
            }

## OU - OrgUnitShiftType [/orgunit/orgUnit_id={orgUnit_id}/orgUnitShiftType/orgUnitShiftType_id={orgUnitShiftType_id}]

### OrgUnitShiftType Delete [DELETE]

Change orgUnitShiftType active attribute to false

+ Parameters

    + orgUnit_id (int) - org.unit ID in the form of integer    
    + orgUnitShiftType_id (number) - ID of the orgUnitShiftType in the form of an integer

+ Response 200 (application/json)

            {
                "shiftType" : {
                    "id": "1"
                    "name": "15",
                    "length": "15",
                    "active": "false"
                }
            }















